# alias db="php vendor/silverstripe/framework/cli-script.php dev/build"
alias db="sake dev/build 'flush=all'"
alias mergedev="git checkout master; git merge develop -m 'merge develop'; git push; git checkout develop"
alias gs="git status"
alias nb="npm run build"
alias apps="cd ~/Documents/apps"
alias wplocal="cd /Users/jackconner/Local\ Sites/"
alias mysql="/Applications/MAMP/Library/bin/mysql --host=localhost -uroot -proot"
alias mysqldump="/Applications/MAMP/Library/bin/mysqldump"
alias vhosts="vi /Applications/MAMP/conf/apache/extra/httpd-vhosts.conf"
